QA-Project/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Course__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instructor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

QA-Project/force-app/main/default/classes/updateOpportunityName.cls
public with sharing class updateOpportunityName {
    public static void updateOppName(List<Opportunity> oppList){

        List<User> uList = [SELECT FirstName, LastName FROM User];
        List<Course__c> courseList = [SELECT Name FROM Course__c];
        String userFirstName;
        String userLastName;
        String courseName;
        for(Opportunity opp : oppList){
            for(User u : uList){
                if(u.id == opp.Instructor__c){
                    userFirstName = u.Firstname;
                    userLastName = u.LastName;
                }
            }

            for(Course__c course : courseList){
                if(course.id == opp.Course_Name__c){
                    courseName = course.Name;
                }
            }
            opp.Name = userFirstName +' ' + userLastName + ' - ' + courseName;
            
        }

        
    }
}