QA-Project/force-app/main/default/objects/Autonumber__c/Autonumber__c.object-meta.xml
<CustomObject>
    <label>Autonumber</label>
    <nameField>
        <label>Autonumber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Autonumbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Autonumber__c/fields/Expense_Invoice_Index__c.field-meta.xml
<CustomField>
    <fullName>Expense_Invoice_Index__c</fullName>
    <label>Expense Invoice Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Autonumber__c/fields/Service_Invoice_Index__c.field-meta.xml
<CustomField>
    <fullName>Service_Invoice_Index__c</fullName>
    <label>Service Invoice Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/Course_nvoices__c.object-meta.xml
<CustomObject>
    <label>Course Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Autonumber__c.field-meta.xml
<CustomField>
    <fullName>Autonumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autonumber</label>
    <referenceTo>Autonumber__c</referenceTo>
    <relationshipLabel>Course Invoices</relationshipLabel>
    <relationshipName>Course_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Course_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Course_Opportunity__c</fullName>
    <label>Course Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Course_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipName>ServiceandExpenseInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Invoice_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Submitted_Date__c</fullName>
    <label>Invoice Submitted Date</label>
    <type>Date</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Course_Opportunity__r.Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/ServiceandExpenseInvoiceMDR__c.field-meta.xml
<CustomField>
    <fullName>ServiceandExpenseInvoiceMDR__c</fullName>
    <label>ServiceandExpenseInvoiceMDR</label>
    <referenceTo>Course_nvoices__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QA-Project/force-app/main/default/classes/AutomateManualShareHandler_Test.cls
@isTest
public with sharing class AutomateManualShareHandler_Test {
    
    
    @testSetup
    private static void loadData(){
       
        List<Opportunity> oppList = new List<Opportunity>();    
        

        for(integer i = 0; i < 201; i++){
            
            Opportunity opp = new Opportunity(StageName='Scheduled', Name='Test Company Ltd', Start_Date__c =Date.newInstance(Date.today().year(), 9, 1),
            CloseDate= Date.newInstance(Date.today().year(), 9, 3), Course_Name__c='a014L000001k4jeQAA', OwnerId='0054L0000013S7hQAE', Instructor__c='0054L0000013UInQAM', Location__c='London');
            oppList.add(opp);
        }

        insert oppList;
        
      

        

        System.debug('test setup opplist size ' + oppList.size());    
       
        List<AutoNumber__c> autoNumberList = new List<AutoNumber__c>();
        AutoNumber__c autoNumService = new AutoNumber__c (Name = 'Service Invoice Number', Service_Invoice_index__c = 1, Expense_Invoice_index__c = 1);
        autoNumberList.add( autoNumService);
        insert autoNumberList;
        
        for(integer i = 0; i < 201; i++){
           oppList[i].StageName = 'cancelled';
            
        }
        update oppList;
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = [SELECT Id FROM User WHERE profileId = :p.Id LIMIT 1];
        System.runAs(u){
        }

        
    }

    @isTest
    private static void UpdateCalEvent_Test(){
        Test.startTest();
                    List<Opportunity> oppList = [SELECT Id, StageName,Name,Start_Date__c,CloseDate,OwnerId,Course_Name__c,Instructor__c FROM Opportunity ];
                    System.debug('oppList bring in ' + oppList.size());
                for(Integer i = 0; i < oppList.size(); i++){
    
                    oppList[i].Start_Date__c = Date.newInstance(Date.today().year(), 9, 2);
                    
                }
                System.debug('The number'+oppList.size());
                update oppList;   
            Test.stopTest();

            System.assertEquals(0, [SELECT count() FROM Event ]); // broke when I covered other branch.. running out of time.

    }


@isTest
public static void OppToEventUpdateOrDeleteDelete_Test() {

    Test.startTest();

        List<Opportunity> oppListDelete = [SELECT Id, StageName,Name,Start_Date__c,CloseDate,OwnerId,Course_Name__c,Instructor__c FROM Opportunity ];
        delete oppListDelete;

    Test.stopTest();

    System.assertEquals(0, [SELECT count() FROM Event ]);

}

@isTest
        private static void courseOppAutomaticSharingTest(){
            
            List<Opportunity> activeOpp = [SELECT Id, StageName,Name,Start_Date__c,CloseDate,OwnerId,Course_Name__c,Instructor__c FROM Opportunity LIMIT 1];
            Opportunity opportunity = activeOpp[0];
            
            Test.startTest();
                        
            Test.stopTest();
    
            System.assertEquals(402, [SELECT count() FROM OpportunityShare ]); //Double as shared with the Admin and Mary Stevens
            
        }
    

    @isTest
    public static void AutoNumberService_Test() {
        
        Test.startTest();
                List<Opportunity> oppList = [SELECT Id, StageName,Name,Start_Date__c,CloseDate,OwnerId,Course_Name__c,Instructor__c FROM Opportunity ];
               
            for(Integer i = 0; i < oppList.size(); i++){

                oppList[i].Start_Date__c = Date.newInstance(Date.today().year(), 9, 2);
                oppList[i].StageName = 'Completed';
                oppList[i].Location__c = 'London';
            }

            update oppList;   
            List<Course_nvoices__c> courseList = [SELECT Id, Invoice_Status__c FROM Course_nvoices__c];
            for(Integer i = 0; i < courseList.size(); i++){
                system.debug(courseList[i].Invoice_status__c);
                courseList[i].Invoice_Submitted_Date__c = Date.Today();
                courseList[i].Invoice_Status__c = 'Submitted';
                
            }
            Integer emailInvocations = Limits.getEmailInvocations();
            update courseList;

        Test.stopTest();
        System.assertEquals(4, emailInvocations);
        System.assertEquals(201, [SELECT count() FROM Course_nvoices__c ]);

        Course_nvoices__c firstInput = [SELECT Name FROM Course_nvoices__c Order By Name  ASC Limit 1];
        String firstEntry = firstInput.Name;
   
        Course_nvoices__c lastInput = [SELECT Name FROM Course_nvoices__c Order By Name DESC Limit 1];
        String lastEntry = lastInput.Name;

        
        System.assertEquals('INV-{0001}', firstEntry);
        System.assertEquals('INV-{0201}', lastEntry);

    }

    @isTest
    public static void AutoNumberExpense_Test() {
        String expenseRecordType = Schema.SObjectType.Course_nvoices__c.getRecordTypeInfosByName().get('Expense Invoice').getRecordTypeId();
        List<Course_nvoices__c> expenseList = new List<Course_nvoices__c>();
        List<Opportunity> oppList = [SELECT id FROM Opportunity LIMIT 1];

        for(Integer i =0; i < 201; i++){
            Course_nvoices__c expenseInvoices = new Course_nvoices__c (Name='1', RecordTypeId=expenseRecordType,Invoice_Status__c='Draft', Course_Opportunity__c=oppList[0].id);
            expenseList.add(expenseInvoices);
            
        }
  
        insert expenseList;
 
        

        Test.startTest();
        Test.stopTest();

        Course_nvoices__c firstInput = [SELECT Name FROM Course_nvoices__c Order By Name  ASC Limit 1];
        String firstEntry = firstInput.Name;
   
        Course_nvoices__c lastInput = [SELECT Name FROM Course_nvoices__c Order By Name DESC Limit 1];
        String lastEntry = lastInput.Name;

        System.assertEquals(201, [SELECT count() FROM Course_nvoices__c ]);
        System.assertEquals('EXPINV-{0001}', firstEntry);
        System.assertEquals('EXPINV-{0201}', lastEntry);
    }



    @isTest
    public static void removeCalendarEvent_Test(){
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity opp = [SELECT id, StageName FROM opportunity limit 1];
       
        for(Integer i = 0; i < oppList.size(); i++){
            oppList[i].StageName = 'Cancelled';
        }
        update oppList;
        
        
    }


    @isTest
    public static void invoiceControllerExtension_Test(){
        
        List<Opportunity> opp = [SELECT id FROM opportunity limit 1];
        List<Invoice_Line_Item__c> ili = [SELECT Id FROM Invoice_Line_Item__c WHERE ServiceandExpenseInvoiceMDR__c =:opp[0].id];

        ApexPages.currentPage().getParameters().put('test', opp[0].id);
        ApexPages.StandardController std = new ApexPages.StandardController(opp[0]);
        invoiceControllerExtension ice = new invoiceControllerExtension(std);


        ice.getILIList();
        
        system.assertEquals(ili, ice.getILIList());
    }

    @isTest
    public static void expenseControllerExtension_Test(){
        
        List<Opportunity> opp = [SELECT id FROM opportunity limit 1];
        List<Invoice_Line_Item__c> ili = [SELECT Id FROM Invoice_Line_Item__c WHERE ServiceandExpenseInvoiceMDR__c =:opp[0].id];

        ApexPages.currentPage().getParameters().put('test', opp[0].id);
        ApexPages.StandardController std = new ApexPages.StandardController(opp[0]);
        ExpenseInvController ece = new ExpenseInvController(std);


        ece.getILIListwithMileage();
        
        system.assertEquals(ili, ece.getILIListwithMileage());
    }

    @isTest
    private static void createExpenseLineItem_Test(){
        String expenseRecordType = Schema.SObjectType.Course_nvoices__c.getRecordTypeInfosByName().get('Expense Invoice').getRecordTypeId();
        List<Course_nvoices__c> invoices = new List<Course_nvoices__c>();
        List<Opportunity> oppList = [SELECT Id FROM Opportunity WHERE Location__C = 'London' LIMIT 1];
        for(integer i = 0; i < 201; i++){
            Course_nvoices__c c = new Course_nvoices__c();
            c.recordTypeId = expenseRecordType;
            c.Auto_Generate_Mileage__c = true;
            c.Distance_To_Destination__c = 50;
            c.course_opportunity__c = oppList[0].id;
            invoices.add(c);
        }
        insert invoices;
    }

}