QA-Project/force-app/main/default/objects/Course_nvoices__c/Course_nvoices__c.object-meta.xml
<CustomObject>
    <label>Course Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <formula>Course_Opportunity__r.Hourly_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hourly Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipName>ServiceandExpenseInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Rate__c</fullName>
    <formula>Invoice_Line_Item__r.Mileage_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mileage Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <label>Hourly Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/Mileage_Cost__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Cost__c</fullName>
    <formula>Distance__c *  Mileage_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mileage Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Rate__c</fullName>
    <defaultValue>0.42</defaultValue>
    <label>Mileage Rate</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/ServiceandExpenseInvoiceMDR__c.field-meta.xml
<CustomField>
    <fullName>ServiceandExpenseInvoiceMDR__c</fullName>
    <label>ServiceandExpenseInvoiceMDR</label>
    <referenceTo>Course_nvoices__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QA-Project/force-app/main/default/classes/ExpenseInvController.cls
public class ExpenseInvController {
	
    private final Invoice_Line_Item__c expenseInvoice;
    public id currentId;
    public ExpenseInvController(ApexPages.standardController std){
         CurrentId = std.getRecord().Id;
    }

    public List<Invoice_Line_Item__c> getILIListwithMileage(){
        List<Invoice_Line_Item__c> ILIList = [SELECT Id, Date__c, Distance__c, 
                                                Hourly_Rate__c, Hours__c, Name, 
                                                RecordTypeId,Amount_del__c, Total_Amount_del__C, Mileage_Cost__c, Mileage_Rate__c, Description__c, ServiceandExpenseInvoiceMDR__c 
                                                FROM Invoice_Line_Item__c WHERE ServiceandExpenseInvoiceMDR__c =:currentId];

        List<Invoice_Line_Item__c> newList = new List<Invoice_Line_Item__c>();
        for(Invoice_Line_Item__c i : ILIList){
            system.debug(i.distance__C);
            if(i.distance__c != null){
                
                newList.add(i);
            }
        }
        
        return newList;
    }

    public List<Invoice_Line_Item__c> getILIListwithoutMileage(){
        List<Invoice_Line_Item__c> ILIList = [SELECT Id, Date__c, Distance__c, 
                                                Hourly_Rate__c, Hours__c, Name, 
                                                RecordTypeId,Amount_del__c, Total_Amount_del__C, Mileage_Cost__c, Mileage_Rate__c, Description__c, ServiceandExpenseInvoiceMDR__c 
                                                FROM Invoice_Line_Item__c WHERE ServiceandExpenseInvoiceMDR__c =: CurrentId];
        
        List<Invoice_Line_Item__c> newList = new List<Invoice_Line_Item__c>();
        for(Invoice_Line_Item__c i : ILIList){
            system.debug(i.distance__C);
            if(i.distance__c == null){
                
                newList.add(i);
            }
        }
        
        return newList;
    }



    public Pagereference saveInvoiceAsPdf(){
        Pagereference pdf = Page.ExpenseInvoiceTOPDF;
        pdf.getParameters().put('id', currentId);

        Attachment attach = new Attachment();

        Blob body;

        try {
            body = pdf.getContent();

        } catch (VisualforceException e ){
            body = Blob.valueOf('some text');
        }

        attach.Body = body;
        Course_nvoices__c course = [SELECT Name FROM Course_nvoices__C WHERE Id=:currentId];
        attach.Name = course.name;
        attach.IsPrivate = false;

        attach.ParentId = currentId;

        insert attach;

        return null;
    }
     
}