QA-Project/force-app/main/default/objects/Course_nvoices__c/Course_nvoices__c.object-meta.xml
<CustomObject>
    <label>Course Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipName>ServiceandExpenseInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Course_Opportunity__r.Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Rate__c</fullName>
    <formula>Invoice_Line_Item__r.Mileage_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mileage Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Rate__c</fullName>
    <defaultValue>0.42</defaultValue>
    <label>Mileage Rate</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/fields/ServiceandExpenseInvoiceMDR__c.field-meta.xml
<CustomField>
    <fullName>ServiceandExpenseInvoiceMDR__c</fullName>
    <label>ServiceandExpenseInvoiceMDR</label>
    <referenceTo>Course_nvoices__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QA-Project/force-app/main/default/objects/Invoice_Line_Item__c/recordTypes/Mileage.recordType-meta.xml
<RecordType>
    <fullName>Mileage</fullName>
    <active>true</active>
    <label>Mileage</label>
</RecordType>

QA-Project/force-app/main/default/classes/ServiceInvoiceLineItemHandler.cls
public with sharing class ServiceInvoiceLineItemHandler {
    public static void createServiceInvoiceLineItem(List<Course_nvoices__c> courseInvoices){
      List<Invoice_Line_Item__c> newILIList = new List<Invoice_Line_Item__c>();
      List<Opportunity> oppList = [SELECT id, Start_Date__c FROM opportunity];
      //system.debug('OppList Size: ' + oppList.size() + 'oppList[0].Start_date__c : ' + oppList[0].Start_Date__c);
      String ServiceRecordType = Schema.SObjectType.Course_nvoices__c.getRecordTypeInfosByName().get('Service Invoice').getRecordTypeId();
      String ExpenseRecordType = Schema.SObjectType.Course_nvoices__c.getRecordTypeInfosByName().get('Expense Invoice').getRecordTypeId();
      String MileageRecordType = Schema.SObjectType.Invoice_Line_Item__c.getRecordTypeInfosByName().get('Mileage').getRecordTypeId();


      Integer day = 0;
      system.debug('create service line item lsit size' + oppList.size());
        for(Course_nvoices__c cInv : courseInvoices){
          System.debug(cInv.location__c);
          System.debug('cInv.recordTypeID: ' + cInv.recordTypeID + ' and expenseRecordType: ' + ExpenseRecordType);
            if(cInv.recordTypeId == ServiceRecordType){
              for(Integer i = 0; i < cInv.duration__c; i++){
                  Invoice_Line_Item__c newILI = new Invoice_Line_Item__c();
                  newILI.ServiceandExpenseInvoiceMDR__c = cInv.Id;
                  newILI.hours__c = 8;
                  newILI.Date__c = oppList[0].Start_Date__c.addDays(i);
                  newILI.Description__c = 'Day of Teaching';
                  newILIList.add(newILI);
                  day++;
              }
            }
            else if(cInv.Location__c != null){
                if(cInv.recordTypeId == ExpenseRecordType ){
                  for(Integer i = 0; i < cInv.Duration__c; i++){
                    for(integer j =0; j < 2; j++){
                      Invoice_Line_Item__c newEILI = new Invoice_Line_Item__c();
                      newEILI.ServiceandExpenseInvoiceMDR__c = cInv.id;
                      newEILI.recordTypeId = MileageRecordType;
                      newEILI.Distance__c = 5;
                      newEILI.mileage_rate__c = 0.42;
                      if(j == 0){
                        newEILI.description__c = 'Travelling To ' + cInv.Location__c;
                      } else {
                        newEILI.description__c = 'Travelling From ' + cInv.Location__c;
                      }
                      
                      newEILI.date__c = oppList[0].Start_Date__c.addDays(i);
                      newILIList.add(newEILI);
                    }
                  }
                }
              }
        }
        insert(newILIList);
    }
}