QA-Project/force-app/main/default/objects/Course_nvoices__c/Course_nvoices__c.object-meta.xml
<CustomObject>
    <label>Course Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA-Project/force-app/main/default/objects/Course_nvoices__c/fields/Course_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Course_Opportunity__c</fullName>
    <label>Course Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Course_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QA-Project/force-app/main/default/classes/InstructorInvoiceHandler.cls
public with sharing class InstructorInvoiceHandler {

    public static void createServiceInvoice(List<Opportunity> courses, List<Opportunity> oldCourses){
        String ServiceRecordType = Schema.SObjectType.Course_nvoices__c.getRecordTypeInfosByName().get('Service Invoice').getRecordTypeId();
        
        List<Course_nvoices__c> newInvList = new List<Course_nvoices__c>();
        Integer i = 0;
        for(Opportunity opp : courses){
           
            if(opp.StageName == 'Completed' && oldCourses[i].StageName != 'Completed'){
                Course_nvoices__c newInv = new Course_nvoices__c();
                newInv.Course_Opportunity__c = opp.Id;
                newInv.recordTypeId = ServiceRecordType;
                newInvList.add(newInv);                
            }
        
            i++;
        }        
        insert newInvList;
    }

    public static void createServiceInvoice(List<Opportunity> courses){
        String ServiceRecordType = Schema.SObjectType.Course_nvoices__c.getRecordTypeInfosByName().get('Service Invoice').getRecordTypeId();
        
        List<Course_nvoices__c> newInvList = new List<Course_nvoices__c>();
        Integer i = 0;
        for(Opportunity opp : courses){
           
            if(opp.StageName == 'Completed'){
                Course_nvoices__c newInv = new Course_nvoices__c();
                newInv.Course_Opportunity__c = opp.Id;
                newInv.recordTypeId = ServiceRecordType;
                newInvList.add(newInv);                
            }
                  
            i++;
        }        
        insert newInvList;
    }
}